# Generated by Django 4.2.2 on 2023-06-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Texto curto'), ('textarea', 'Texto longo'), ('email', 'E-mail'), ('checkbox', 'Checkbox'), ('select', 'Lista'), ('radio', 'Seleção única')], max_length=255)),
                ('choices', models.ManyToManyField(blank=True, to='proposal.choice')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('main', models.BooleanField(default=False)),
                ('fields', models.ManyToManyField(blank=True, to='proposal.field')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.JSONField()),
                ('status', models.CharField(blank=True, choices=[('True', 'Aprovada'), ('False', 'Negada')], max_length=255, null=True)),
                ('needs_human_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalform')),
            ],
        ),
    ]
