# Generated by Django 4.2.2 on 2023-06-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_auto_20230618_1633'),
    ]

    def generate_fields_and_proposal_form(apps, schema_editor):
        from proposal.models import Choice, Field, ProposalForm

        choices = []

        pf, created = Choice.objects.get_or_create(text="Física")
        choices.append(pf.id)

        pj, created = Choice.objects.get_or_create(text="Jurídica")
        choices.append(pj.id)

        pessoa, created = Field.objects.get_or_create(name="Pessoa", type="radio")
        pessoa.choices.set(choices)

        doc,   created = Field.objects.get_or_create(name="Documento", type="text")
        email, created = Field.objects.get_or_create(name="Email", type="email")
        desc,  created = Field.objects.get_or_create(name="Descrição", type="textarea")

        fields = [pessoa.id, doc.id, email.id, desc.id]

        main_form = ProposalForm.objects.filter(main=True)
        if main_form.count() > 0:
            main_form.delete()

        proposal_form, creted = ProposalForm.objects.get_or_create(name="Gerado automaticamente", main=True)
        proposal_form.fields.set(fields)

    operations = [
        migrations.RunPython(generate_fields_and_proposal_form),
    ]
