# Generated by Django 4.2.2 on 2023-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20230618_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Avaliação necessária'), ('True', 'Aprovada'), ('False', 'Negada')], max_length=255, null=True),
        ),
    ]
