version: "3.8"

services:

  django:
    build: .
    container_name: django
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/proposal/
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A lfg_system.celery worker --loglevel=info -P eventlet
    volumes:
      - .:/usr/src/proposal
    depends_on:
      - django
      - redis

  redis:
      image: "redis:alpine"